"""
Safety Validation Layer for LLM-generated SQL.

This module provides a defense-in-depth strategy for executing SQL generated by Large 
Language Models (LLMs). LLMs can occasionally generate destructive queries or be 
manipulated through prompt injection into generating malicious SQL (SQL injection).

Defense-in-Depth Strategy:
1. Lexical Sanitization: Removing markdown artifacts and formatting errors often produced by LLMs.
2. Allow-listing: Strictly enforcing that the query begins with `SELECT`, blocking all other types.
3. Length Constraints: Preventing excessively long queries that could cause Denial of Service (DoS).
4. Structural Validation: Detecting multiple statement executions (semicolon chaining) to prevent secondary payload execution.
5. Pattern Matching: Using word-boundary regular expressions to detect destructive keywords anywhere in the query (e.g., inside CTEs or subqueries).
6. Dialect-specific Protections: Blocking SQLite-specific vulnerabilities like dynamic extension loading or database attachment.

This multi-layered approach ensures that even if one check is bypassed or malformed, 
subsequent checks catch malicious intent before execution.
"""

import re
from typing import Tuple

# Maximum allowed query length to prevent DoS attacks
MAX_QUERY_LENGTH = 2000

# Keywords that are strictly forbidden anywhere in the SQL query
BLOCKED_KEYWORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "CREATE",
    "TRUNCATE",
    "EXEC",
    "EXECUTE"
]


def sanitize_sql(sql: str) -> str:
    """
    Cleans and standardizes the LLM-generated SQL string.
    
    LLMs frequently wrap code in markdown blocks or include trailing punctuation.
    This function prepares the query for execution and validation by removing these artifacts.
    
    Args:
        sql: The raw SQL string from the LLM.
        
    Returns:
        A cleaned, executable SQL string.
    """
    if not sql:
        return ""
        
    # Remove markdown code block markers that the LLM might have generated
    # This removes ```sql and ``` optionally with trailing whitespaces
    sql = re.sub(r"```[a-zA-Z]*\n?", "", sql)
    sql = re.sub(r"```", "", sql)
    
    # Strip leading and trailing whitespace
    sql = sql.strip()
    
    # Remove trailing semicolons (we will add one or handle it in the DB engine if needed)
    sql = re.sub(r";+\s*$", "", sql)
    
    return sql


def _check_empty(sql: str) -> str | None:
    """Checks if the SQL query is empty or None."""
    if not sql or not sql.strip():
        return "Query blocked: Query is empty."
    return None


def _check_length(sql: str) -> str | None:
    """Checks if the SQL query exceeds the maximum allowed length."""
    if len(sql) > MAX_QUERY_LENGTH:
        return f"Query blocked: Query exceeds maximum length of {MAX_QUERY_LENGTH} characters."
    return None


def _check_starts_with_select(sql: str) -> str | None:
    """
    Enforces that the query is a SELECT statement.
    This is our primary allow-list mechanism.
    """
    if not sql.upper().startswith("SELECT"):
        # Find the first word to provide a helpful error message
        first_word = sql.split()[0] if sql.split() else "Unknown"
        return f"Query blocked: Only SELECT statements are allowed. Detected: {first_word.upper()}"
    return None


def _check_multiple_statements(sql: str) -> str | None:
    """
    Detects if multiple SQL statements are chained together.
    
    Attackers might try to bypass the SELECT allow-list by chaining a destructive 
    command after a valid SELECT (e.g., `SELECT * FROM users; DROP TABLE users`).
    """
    # Remove all string literals (single and double quoted) to avoid false positives 
    # where a semicolon is legitimately used within a string.
    # The pattern matches anything between non-escaped single or double quotes.
    sql_without_strings = re.sub(r"'[^']*'|\"[^\"]*\"", "", sql)
    
    # After removing strings, check if there is a semicolon followed by any non-whitespace character.
    # This indicates a second statement is attempting to execute.
    if re.search(r";\s*\w+", sql_without_strings):
        return "Query blocked: Multiple SQL statements detected. This could indicate SQL injection."
    return None


def _check_dangerous_keywords(sql: str) -> str | None:
    """
    Scans for destructive keywords anywhere in the query.
    
    Even if a query starts with SELECT, it might contain malicious subqueries or CTEs.
    We use word boundaries (\\b) to ensure we don't accidentally match parts of column 
    names or strings (e.g., preventing a false positive on a column named 'is_deleted').
    """
    # Create an OR-separated list of keywords for the regex
    keywords_pattern = "|".join(BLOCKED_KEYWORDS)
    
    # \\b asserts a word boundary, (?i) makes it case-insensitive
    pattern = rf"(?i)\b({keywords_pattern})\b"
    
    match = re.search(pattern, sql)
    if match:
        return f"Query blocked: Dangerous keyword {match.group(1).upper()} detected within query."
    return None


def _check_sqlite_specific_attacks(sql: str) -> str | None:
    """
    Detects SQLite-specific vulnerabilities.
    
    - ATTACH DATABASE: Can be used to attach a remote/malicious database.
    - LOAD_EXTENSION: Can be used to load malicious native code extensions.
    """
    upper_sql = sql.upper()
    if "ATTACH DATABASE" in upper_sql or "ATTACH" in upper_sql and "DATABASE" in upper_sql:
        return "Query blocked: SQLite ATTACH DATABASE command detected."
    if "LOAD_EXTENSION" in upper_sql:
        return "Query blocked: SQLite LOAD_EXTENSION command detected."
    return None


def _check_union_injection(sql: str) -> str | None:
    """
    Detects UNION-based injection attempts that combine with dangerous operations.
    While UNION itself is a valid SELECT operator, it is highly utilized in SQLi.
    We combine checking for UNION with typical schema-probing or destructive patterns.
    """
    upper_sql = sql.upper()
    if "UNION" in upper_sql:
        # If UNION is used with PRAGMA or sqlite_master (SQLite schema tables)
        if "SQLITE_MASTER" in upper_sql or "SQLITE_TEMP_MASTER" in upper_sql or "PRAGMA" in upper_sql:
             return "Query blocked: Suspicious UNION-based injection attempt targeting schema."
    return None


def validate_sql(sql: str) -> Tuple[bool, str]:
    """
    Validates a SQL query string to ensure it is safe for execution.
    
    This function applies a series of checks in a specific order to implement 
    a defense-in-depth strategy against prompt injection and malicious SQL generation.
    
    Args:
        sql: The sanitized SQL query string to validate.
        
    Returns:
        A tuple of (is_valid, message).
        If is_valid is True, message is 'Valid'.
        If is_valid is False, message contains the specific reason for rejection.
    """
    # Define the validation chain
    validators = [
        _check_empty,
        _check_length,
        _check_starts_with_select,
        _check_multiple_statements,
        _check_dangerous_keywords,
        _check_sqlite_specific_attacks,
        _check_union_injection
    ]
    
    for validator in validators:
        error_msg = validator(sql)
        if error_msg:
            return False, error_msg
            
    return True, "Valid"
